### ISSUE TITLE
Please add a screen shot

### ISSUE THREAD

**Issue by unixorn** [supertassu/another-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots so that users can see what they look like without having to install them.

**Comment by supertassu** [comment]
Done!

Just out of curiosity, how did you find this?

**Comment by unixorn** [comment]
Every couple of days I do a github search for zsh themes and zsh plugins so I can update the list.
